# 1-Python Data Types
* int/float
* strings
* booleans

## a-Int/Float 

In [ ]:
# Integers and floats
x = 1
y = 1.0

In [ ]:
type(y)

float

### Mathmatical Operations

In [ ]:
#addition
x + 1

2

In [ ]:
#subtraction
y - 3

-2.0

In [ ]:
#multiplication
x * 4

4

In [ ]:
#division
y / 8

0.125

In [ ]:
#exponents
(x + 1) ** 2

4

In [ ]:
#remainder
x % 3

#useful for checking if even/odd

1

In [ ]:
#floor division
9 // 2

4

### Comparison Operators

In [ ]:
x > 1

False

In [ ]:
x >= 1

True

In [ ]:
x <= 1

True

In [ ]:
x == 1

True

In [ ]:
x != 1

False

## b-Strings

In [ ]:
strang = 'this is a string'
my_strang = "this is also a string"

In [ ]:
type(strang)

str

In [ ]:
len(strang)

16

In [ ]:
strang[:10]

'this is a '

In [ ]:
strang + my_strang

'this is a stringthis is also a string'

In [ ]:
import string
string.ascii_letters

'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'

In [ ]:
string.ascii_lowercase
string.ascii_uppercase

'ABCDEFGHIJKLMNOPQRSTUVWXYZ'

F-String

In [ ]:
num = 25; name = 'zorp'
f'{name} is {num} years old'

'zorp is 25 years old'

.format()

In [ ]:
'{} is {} years old'.format(num, name)

'25 is zorp years old'

### Methods

.upper() and .lower()

In [ ]:
my_strang.upper()

'THIS IS ALSO A STRING'

In [ ]:
my_strang.upper().lower()

'this is also a string'

.split()

In [ ]:
my_strang.split()

['this', 'is', 'also', 'a', 'string']

In [ ]:
my_strang.split('i')

['th', 's ', 's also a str', 'ng']

.join()


In [ ]:
'_'.join(my_strang.split())

'this_is_also_a_string'

In [ ]:
'-'.join(['1', '2', '3'])

'1-2-3'

.replace()

In [ ]:
strang.replace('there', 'armadillo')

'hello armadillo'

.count()

In [ ]:
strang.count('e')

3

.startswith()
.endswith()

In [ ]:
strang.startswith('hello')

True

In [ ]:
strang.endswith('fart_breath')

False

.strip()

In [ ]:
baddata = "          This is a sentence              "
baddata.strip()

'This is a sentence'

In [ ]:
baddata.lstrip()

'This is a sentence              '

In [ ]:
baddata.rstrip()

'          This is a sentence'

.zfill() - left padding

In [ ]:
zip = '2130'
zip.zfill(5)

'02130'

find() and index()

In [ ]:
line = 'the quick brown fox jumped over a lazy dog   '
line.find('fox')
#returns index where first occurence is found

16

In [ ]:
line = 'the quick brown fox jumped over a lazy dog'
line.rindex('dog')
#returns index where first occurence is found

39

The only difference between find() and index() is their behavior
when the search string is not found; find() returns -1, while
index() raises a ValueError:


Checking methods

Big 3: .isalpha() .isnumeric() .isalnum()

Others: <br >
.isdecimal()
.isdigit()
.isidentifier()
.islower()
.isspace()
.isprintable()
.istitle()
.isupper()

In [ ]:
x = '10'
y = 'This is a sentence'
z = '1A0'

.isalpha() <br >
checks if a string is all alphabetical characters <br >
(note spaces not considered aphabetical)

In [ ]:
print(y)
y.isalpha()

This is a sentence


False

In [ ]:
print(y.replace(' ', ''))
y.replace(' ', '').isalpha()

Thisisasentence


True

.isnumeric()

In [ ]:
x.isnumeric()

True

In [ ]:
not x.isnumeric()

False

.isalnum() <br >
checks if alphanumeric

In [ ]:
z.isalnum()

True

In [ ]:
x.isalnum()

True

In [ ]:
y.replace(' ', '').isalnum()

True

In [ ]:
y.isalnum()
#spaces messing everything up again

False

## c-Booleans

In [ ]:
true = True
type(true)

#note - case sensitivity - true and True are fundamentally different in python

bool

In [ ]:
false = False

True == 1 <br >
False == 0

In [ ]:
True + True

2

# 2-Python Data Structures 
* tuples - ( )
* lists - [ ]
* sets - { }
* dictionaries - { key : value}

### a-Tuples 

Immutable - items within a tuple cannot be updated with new values <br >
Can hold variety of data types

In [ ]:
tup = 1,2,'hi'

In [ ]:
tup

(1, 2, 'hi')

In [ ]:
type(tup)

tuple

In [ ]:
tup[2] 

3

## b-Lists

Mutable - items within a list can be updated with new values by accessing it's index <br >
Can hold variety of data types

In [ ]:
lizt = [1,2,3, 'a',5,'c',9]

In [ ]:
type(lizt)

list

In [ ]:
#list within list
[1,2,[3,4], [5]]

[1, 2, [3, 4], [5]]

### List Methods

In [ ]:
lizt.append(3)
lizt

[1, 2, 3, 'a', 5, 'c', 9, 3]

In [ ]:
lizt.pop()
#returns and removes value at last index in list

3

In [ ]:
lizt.remove(3)
lizt
#removes first instance in list

[1, 2, 'a', 5, 'c', 9]

### List Indexing

Can access individual values or range of values <br >
-range - [start, up to but not including] 

In [ ]:
lizt[0]

1

In [ ]:
lizt[-1]

9

Range of values

In [ ]:
lizt[1:3]

[2, 'a']

In [ ]:
lizt[:3]

[1, 2, 'a']

In [ ]:
lizt[-2:]

['c', 9]

Reversing order

In [ ]:
lizt[::-1]

[9, 'c', 5, 'a', 2, 1]

## c-Sets

Sets store unique items in no particular order (no indexing)



In [ ]:
set(lizt)
#returns 1 of each unique items in list

{1, 2, 5, 9, 'a', 'c'}

In [ ]:
set([1,1,1,2,2,1,3,4,3])

{1, 2, 3, 4}

### Set Methods

.union(), .intersection(), .difference()

In [ ]:
s = set(lizt)
s2 = set([1,1,1,2,2,1,3,4,3])

In [ ]:
s.union(s2)
#all items from both sets

{1, 2, 3, 4, '5', 'a'}

In [ ]:
s.intersection(s2)
#items present in both sets

{1, 2, 3}

In [ ]:
s.difference(s2)
#values in s not in s2

{'5', 'a'}

In [ ]:
s2.difference(s)
#values in s2 not in s

{4}

.add(), .remove(), .pop()

In [ ]:
s.add('b')
s

{1, 2, 3, '5', 7, 'a', 'b'}

In [ ]:
s.remove(7)
s

{1, 2, 3, '5', 'a'}

In [ ]:
s.pop()
#pop - returns and removes first (lowest/alphabetic) item

2

## d-Dictionaries

Key value pairs


In [ ]:
dikt = {'a':1, 'b':2, 'c':3}
dikt

{'a': 1, 'b': 2, 'c': 3}

In [ ]:
dikt.keys()

dict_keys(['a', 'b', 'c'])

In [ ]:
dikt.values()

dict_values([1, 2, 3])

Accessing values with keys

In [ ]:
dikt['b']

2

In [ ]:
dikt['c'] = 4
dikt
#since keys are immutable assigning new value to a key that already exists simply updates the value for the key

{'a': 1, 'b': 2, 'c': 4}

### Dictionary Comprehension

# 3-Numpy

* from other objects
* on the fly
* basic operations
* axis

In [ ]:
import numpy as np

### a-Creating numpy array objects

from other objects:

In [ ]:
z = [1,2,3]
np.array(z)

array([1, 2, 3])

In [ ]:
np.array([4,5,6])

array([4, 5, 6])

on the fly:

from range:

In [ ]:
z = np.arange(1,11, 2)
z
#arange()

array([1, 3, 5, 7, 9])

from random:

In [ ]:
x = np.random.rand(5,3)
x
#returns array of random numbers - 5 rows by 3 columns

array([[0.34145179, 0.45550371, 0.82686627],
       [0.07229836, 0.4240637 , 0.50287842],
       [0.12072486, 0.81630218, 0.72828833],
       [0.42427003, 0.18609768, 0.63199893],
       [0.08660964, 0.02619942, 0.05346587]])

array attributes:

In [ ]:
x.shape

(5, 3)

In [ ]:
x.ndim

2

In [ ]:
x.transpose().shape

(3, 5)

In [ ]:
type(x)

numpy.ndarray

### b-Basic Operations

In [ ]:
x.sum()


6.845641697176936

In [ ]:
x.mean()

0.4563761131451291

In [ ]:
x.std()

0.3411079630166555

### c-Indexing

In [ ]:
x[0,0]
#first row first column

0.2551366618911596

In [ ]:
x[0:3,0]
#first three rows of first column

array([0.25513666, 0.92944577, 0.86112086])

In [ ]:
x[:,0]
#returns all rows in first column

array([0.25513666, 0.92944577, 0.86112086, 0.85943711, 0.03293578])

In [ ]:
x[0,:]
#returns all columns in first row

array([0.25513666, 0.26897322, 0.18368576])

In [ ]:
#can update a value if we want
x[2,1] = .69429
x

array([[0.25513666, 0.26897322, 0.18368576],
       [0.92944577, 0.88169437, 0.27601027],
       [0.86112086, 0.69429   , 0.8960879 ],
       [0.85943711, 0.57182058, 0.00448691],
       [0.03293578, 0.66548321, 0.05111696]])

In [ ]:
#reversing array
x[::-1,::-1]

array([[0.05111696, 0.66548321, 0.03293578],
       [0.00448691, 0.57182058, 0.85943711],
       [0.8960879 , 0.69429   , 0.86112086],
       [0.27601027, 0.88169437, 0.92944577],
       [0.18368576, 0.26897322, 0.25513666]])

### d-Broadcasting - performing operations on entire array 

In [ ]:
z = np.array([1,2,3,4])
z * 3
#can perform operations on entire array, don't have to iterate accross every item like we would have to do with a list

array([ 3,  6,  9, 12])

### e-Reshaping


In [ ]:
z = np.arange(1,10)
z

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
z.shape

(9,)

In [ ]:
z = z.reshape(3,3)
z

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### f-Filtering

In [ ]:
# we can generate an array of booleans for subsetting - broadcasted accross array
z>5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [ ]:
#can also do complex logic - logical and
np.logical_and(z>0, z<5)

array([[ True,  True,  True],
       [ True, False, False],
       [False, False, False]])

In [ ]:
#logical or
np.logical_or(z>0, z<5)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

.where()

In [ ]:
np.where(z>3)
#returns positions of where values exist that meet condition specified in where

(array([1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2]))

.logical_and(), logical_or()

In [ ]:
np.logical_and(z>3, z<6)

array([[False, False, False],
       [ True,  True, False],
       [False, False, False]])

In [ ]:
np.logical_or(z >1, z <4)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

Example

In [ ]:
# Let's see this in action
x = np.random.randint(0, 10, size=100)
print(x.shape)
print(x.ndim)
x[:5]

(100,)
1


array([6, 0, 9, 8, 5])

In [ ]:
#save a variable to store our test results
tests = x>=7
tests[:5]

array([False, False,  True,  True, False])

In [ ]:
#both arrays have the same shape
x.shape == tests.shape

True

In [ ]:
#finally, keep just those that meet our criteria
# WE CAN ONLY KEEP TRUE VALUES
keep = x[tests]
keep.shape
#only kept 29 values where x>=7

(29,)

### g-Numpy Axes

[Link explaining numpy axes](https://www.sharpsightlabs.com/blog/numpy-axes-explained/)

In [ ]:
#axis = 0 - rows
#axis = 1 - columns

#usually rows are observations and columns are attributes about those observations

In [ ]:
a = np.random.randint(0,100, size = (3,7))
a

array([[22, 52, 99, 63, 13, 29, 70],
       [97, 56, 71, 42, 28, 29, 65],
       [79, 60, 39, 21, 35, 90, 87]])

In [ ]:
a.sum(axis = 0)
#summing by compressing on rows (axis = 0)

array([198, 168, 209, 126,  76, 148, 222])

In [ ]:
a.sum(axis = 1)
#summing by compressing across columns (axis = 1)

array([348, 388, 411])

# 4-Control Structure and Loops

* For loop
* while loop
* list comprehension

## a-For Loop

iterates over an iterable (range, string, list)

In [ ]:
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
#strings are iterables
strang = 'Scott'
for char in strang:
  print(char)

S
c
o
t
t


In [ ]:
#iterating over list
lizt = [5,6,7,8]
for i in lizt:
  print(i)

#or

# for i in range(len(lizt)):
#   print(lizt[i])

5
6
7
8


In [ ]:
x = []
for i in range(10):
  print(i)
  tmp = i ** 2 
  x.append(tmp)

x

0
1
2
3
4
5
6
7
8
9


[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [ ]:
i
#i variable is accessible, it is simply the last item it takes on in the loop

9

### Checking if iterable

In [ ]:
from collections.abc import Iterable

In [ ]:
isinstance('BA765', str)

True

In [ ]:
isinstance(2,Iterable)

False

In [ ]:
isinstance('BA765', Iterable)

True

In [ ]:
isinstance(range(54), Iterable)

True

### Bonus


Enumerate

In [ ]:
L = [2, 4, 6, 8, 10]
# for i in range(len(L)):
# print(i, L[i])

for i, val in enumerate(L):
 print(i, val)


0 2
1 4
2 6
3 8
4 10


Zip

In [ ]:
L = [2, 4, 6, 8, 10]
R = [3, 6, 9, 12, 15]
for lval, rval in zip(L, R):
  print(lval, rval)


2 3
4 6
6 9
8 12
10 15


Map <br >
The map iterator takes a function and applies it to the values in an
iterator:


In [ ]:
square = lambda x: x ** 2
for val in map(square, range(10)):
  print(val, end=' ')

0 1 4 9 16 25 36 49 64 81 

Fileter <br >
The filter iterator looks similar, except it only passes through val‐
ues for which the filter function evaluates to True:

In [ ]:
# find values up to 10 for which x % 2 is zero
is_even = lambda x: x % 2 == 0
for val in filter(is_even, range(10)):
  print(val, end=' ')


0 2 4 6 8 

### List Comprehension + Others (Dict - Set)

List Comprehension

In [ ]:
r = [i**2 for i in range(10)]
r

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [ ]:
#with conditions
p = [i**2 for i in range(10) if i > 4]
p

[25, 36, 49, 64, 81]

Set Comprehension

In [ ]:
{n**2 for n in range(10)}
#outputs a set

{0, 1, 4, 9, 16, 25, 36, 49, 64, 81}

Dictionary Comprehension

In [ ]:
{n:n**2 for n in range(6)}


{0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25}

### Generators

* Similar to list comprehension - uses parentheses instead of square brackets

In [ ]:
G =(n ** 2 for n in range(12))
G

<generator object <genexpr> at 0x7f21134dc048>

A generator expression is essentially a list comprehension in which
elements are generated as needed rather than all at once

Useful when needing listlike properties, but saves on memory and computational resources

In [ ]:
for val in G:
  print(val)
  print(' ')

  

0
 
1
 
4
 
9
 
16
 
25
 
36
 
49
 
64
 
81
 
100
 
121
 


A list can be iterated multiple times; a generator expression is single use

## b-While loop

In [ ]:
i = 0
while i <5:
  print(i)
  i = i+1

0
1
2
3
4


## c-If Statement

In [ ]:
x = 3
if x < 5:
  print('hello')
  

hello


In [ ]:
'''
if value:
  something
elif other val:
  something else
else:
  some final thing
'''

'\nif value:\n  something\nelif other val:\n  something else\nelse:\n  some final thing\n'

In [ ]:
x = 1
if x == 0:
  print('0')
elif x > 0:
  print('pos')
else:
  print('neg')

pos


## d-Try-Except 

The `try` block lets you test a block of code for errors.

The `except` block lets you handle the error.

The `finally` block lets you execute code, regardless of the result of the try- and except blocks.

**Exception Handling**

When an error occurs, or exception as we call it, Python will normally stop and generate an error message.

These exceptions can be handled using the `try` statement:

In [ ]:
try:
  print(float('hello'))
except:
  print("An exception occurred")

An exception occurred


Can specify a specific type of error

In [ ]:
try:
  print(float(qrz)) # var not defined 
except ValueError:
  print("Must pass numerical argument")
except:
  print("Something else went wrong")

Something else went wrong


**Finally**

The finally block, if specified, will be executed regardless if the try block raises an error or not.

In [ ]:
try:
  print(float('hello'))
except:
  print("Something went wrong")
finally:
  print("The 'try except' is finished")

Something went wrong
The 'try except' is finished


# 5-Functions 

## Writing Basics

Single Parameter

In [ ]:
def myfunc(x):
  """returns input squared"""
  if not isinstance(x, int):
    return(print('x must be an integer'))
  x = x**2
  return(x)

In [ ]:
help(myfunc)

Help on function myfunc in module __main__:

myfunc(x)
    returns input squared



In [ ]:
myfunc(5)

25

Multiple Parameter

In [ ]:
def tothe(x,y):
  """returns x to the y power"""
  if (not isinstance(x, int)) or (not isinstance(y, int)):
    return(print('x and y must both be integers'))
  z = x ** y
  return z

In [ ]:
tothe(3,4)

81

In [ ]:
3 **4

81

Multiple Return Values

In [ ]:
def height(inches):
  """returns height in feet/inches"""
  feet = inches // 12
  plus_inch = inches % 12
  return (feet, plus_inch) #can use tuple to return multiple values (or list, dict,set)

In [ ]:
height(69)

(5, 9)

In [ ]:
type(height(69))

tuple

Default Arguments

In [ ]:
def tothe(x,y = 2):
  """returns x to the y power
  default exponent is 2"""
  if (not isinstance(x, int)) or (not isinstance(y, int)):
    return(print('x and y must both be integers'))
  z = x ** y
  return z

In [ ]:
tothe(5)

25

## Flexible arguments (*args and **kwargs)

variable-length arguments (varargs):<br>
-arguments that can take an unspecified amount of input. When these are used, the programmer does not need to wrap the data in a list or an alternative sequence.

'*args

In [ ]:
def add_all(*args):
  "summ all values in *args together"
  sum_all = 0

  for num in args:
    sum_all += num

  return sum_all

In [ ]:
add_all(4,3,8,6.5)

21.5

You may be thinking that the solution with *args is very similar to the list solution. That's because *args is internally a Tuple, which is an iterable sequence similar to lists. If you'd like to verify it's type, you can enter the code in your Python interpreter:



In [ ]:
tup = 1,2,3,5,7
tup[3]

5

> Note: args is just a name, you can name that vararg anything as long as it is preceded by a single asterisk (*). It's best practice to keep naming it args to make it immediately recognizable.

'** kwargs

What makes `**kwargs` different is that it allows you to pass a variable number of keyword arguments to functions. Recall from the previous video that, within the function definition, `kwargs` is a dictionary.

In [ ]:
def print_all(**kwargs):
  """print out all key-value pairs in **kwargs."""

  for key, value in kwargs.items():
    print(key + ": " + value)

In [ ]:
print_all(name = 'dumbledore', job = 'headmaster')

name: dumbledore
job: headmaster


Since `**kwargs` is a dictionary, you can iterate over them like any other using the `.items()` method:

In [ ]:
dikt= {'hello':1, 'world':2, 'maria':4}
dikt.items()

dict_items([('hello', 1), ('world', 2), ('maria', 4)])

**Combining Varargs and Keyword Arguments** <br>
Quite often we want to use both `*args` and `**kwargs together`, especially when writing Python libraries or reusable code. Lucky for us, `*args` and `**kwargs` play nicely together, and we can use them in the following way:

In [ ]:
def combined_varargs(*args, **kwargs):
    print(args)
    print(kwargs)

combined_varargs(1, 2, 3, a="hi")

(1, 2, 3)
{'a': 'hi'}


When mixing the positional and named arguments, positional arguments must come **before** named arguments. Furthermore, arguments of a fixed length come before arguments with variable length. Therefore, we get an order like this:

1. Known positional arguments
2. *args
3. Known named arguments
4. **kwargs

In [ ]:
def super_function(num1, num2, *args, callback=None, messages=[], **kwargs):
    print(str(num1 + num2))
    print(args)
    print(callback)
    if num1 % 2 == 0:
      messages.append('even')
    else:
      messages.append('odd')
    print(messages)
    print(kwargs)

super_function(1,2,10,100,kw1 = 5, kw2 = 10)


3
(10, 100)
None
['odd']
{'kw1': 5, 'kw2': 10}


## Function Best Practices

**Docstrings**

In [ ]:
def functin_name(arguments):
  """ 
  Anatomy of a docstring - good one contains:
  Description of what the function does
  Description of the arguments, if any
  Description of the return value, if any
  Description of the errors raised, if any
  Optional extra notes or examples of usage
  """
  pass

In [ ]:
help(functin_name)

Help on function functin_name in module __main__:

functin_name(arguments)
    Anatomy of a docstring - good one contains:
    Description of what the function does
    Description of the arguments, if any
    Description of the return value, if any
    Description of the errors raised, if any
    Optional extra notes or examples of usage



In [ ]:
functin_name.__doc__
#.__doc__ attribute contains raw text of docstring

' \n  Anatomy of a docstring - good one contains:\n  Description of what the function does\n  Description of the arguments, if any\n  Description of the return value, if any\n  Description of the errors raised, if any\n  Optional extra notes or examples of usage\n  '

Docstring formats:
* Google Style
* Numpydoc

^two popular styles

> Google style:

In [ ]:
def function(arg1, arg2 =42):
  """Description of what the function does.

  Args:
    arg_1 (str): Description of arg_1

    arg_2 (int, optional): Write optional when an argument has a default value.

  Returns:
    bool: Optional description of the return value

  Raises:
    ValueError: include any error types that the function intentionally raises
  
  Notes:
    see blah for more info

> Numpydoc:

In [ ]:
def function(arg1, arg2 =42):
  """
  Description of what the function does.

  Parameters
  ----------
  arg_1: expected type of arg_1 
    Description of arg_1

  arg_2 int, optional 
    Write optional when an argument has a default value.
    Default = 42

  Returns
  -------
  The type of the return value
    Can include description of the return value
    Replace "returns" with "yields" if function is a generator

 

**DRY (Don't repeat yourself) and "Do One Thing"**


copying and pasting can lead to issues!

functions can be used to avoid repeating lines

functions should be split into functional areas (function should "do one thing" only)

**Mutable vs Immutable types as arguments**

When you need to set a mutable variable as a default argument, always use None and then set the value in the body of the function. This prevents unexpected behavior like adding multiple columns if you call the function more than once.

In [ ]:
def add_to_list(*args, lizt = None):
  if lizt is None:
    lizt = []
  for i in args:
    lizt.append(i)
  return lizt
add_to_list(1,2,3)

[1, 2, 3]

In [ ]:
add_to_list(3,4,5)
# values not saved from last time running the function!

[3, 4, 5]

In [ ]:
add_to_list(5,6,7, lizt = [1,2,3,4])

[1, 2, 3, 4, 5, 6, 7]

## Context Managers

A context manager: 
* sets up a context
* runs code
* removes the context

In [ ]:
with open('sample_data/README.md') as my_file:
  text = my_file.read()
  length = len(text)

print('The file is {} characters long'.format(length))

The file is 930 characters long


`open` does three things:
* Sets up a context by opening file
* Lets you run any code you want on file
* Removes the context by closing the file

>Using a context manager:

with < context-manager >(< args >) as < variable name >
<br>    '# run code here
<br>    '# this code is running 'inside the context'

**Writing context managers**




Two ways of writing:
* Class-based
* Function-based

Course focuses on function-based

How to create a context manager:
1. Define a function
2. (optitonal) add any set up code your context needs
3. use the 'yield' keyword (indicated special kind of function)
4. (optional) add any teardown code your context needs
5. Add the `@contextlib.contextmanager` decorator

In [ ]:
import contextlib
@contextlib.contextmanager
def my_context():
  print('hello')
  yield 42                   # yield keyword indicates value will be returned, but rest of function will be finished at some point in future
  print('goodbye')

In [ ]:
with my_context() as foo:
  print('foo is {}'.format(foo))

hello
foo is 42
goodbye


Timer context manager:

In [ ]:
import time
# Add a decorator that will make timer() a context manager
@contextlib.contextmanager
def timer():
  """Time the execution of a context block.

  Yields:
    None
  """
  start = time.time()
  # Send control back to the context block
  yield start
  end = time.time()
  print('Elapsed: {:.2f}s'.format(end - start))

with timer():
  print('This should take approximately 0.25 seconds')
  time.sleep(0.25)

This should take approximately 0.25 seconds
Elapsed: 0.25s


>Advanced topics

Context manager patterns:
* Open - Close
* Lock - Release
* Change - Reset
* Enter - Exit
* Start - Stop
* Setup - Teardown
* Connect - Disconnect

**Nested contexts**

In [ ]:
def copy(src, dst):
  """Copy contents of one file to another.

  Args:
    src (str): File name of the file to be copied
    dst (str): Where to write the new file.
  """
  # Open both files
  with open(src) as f_src:
    with open(dst, 'w') as f_dst:
      # Read and write each line, one at a time
      for line in f_src:
        f_dst.write(line)
copy('sample_data/README.md', 'copy.txt')

In [ ]:
!ls

copy.txt  sample_data


In [ ]:
! head copy.txt

This directory includes a few sample datasets to get you started.

*   `california_housing_data*.csv` is California housing data from the 1990 US
    Census; more information is available at:
    https://developers.google.com/machine-learning/crash-course/california-housing-data-description

*   `mnist_*.csv` is a small sample of the
    [MNIST database](https://en.wikipedia.org/wiki/MNIST_database), which is
    described at: http://yann.lecun.com/exdb/mnist/



## Decorators

Powerful way to modify the behavior of functions

**Python functions are objects**

>Functions as variables

In [ ]:
def my_function():
  print('Hello')
x = my_function    #without parenthesis means assigning function to x, with paren means assigning output of function to x
type(x)

function

In [ ]:
x()

Hello


List of functions:

In [ ]:
lof = [my_function, open, print]
lof[2]('I am printing with an element of a list!')

I am printing with an element of a list!


In [ ]:
dof = {'func1':my_function, 'func2':open, 'func3':print}
dof['func3']('YellowWorld')

YellowWorld


>Functions as arguments

In [ ]:
def has_docstring(func):
  """check to see if function passed has a docstring"""
  return func.__doc__ is not None 

has_docstring(my_function), has_docstring(print)

(False, True)

**Scope**

Scope Order: Local -> Nonlocal -> Global -> Builtin

In [ ]:
x = 1
y = 2
z = 3  #global
def fun():
  y = 20  #nonlocal (nested function)
  def fun1():
    x = 10     #local 
    print(x,y,z, False) # false is built-in, doesn't need to be defined anywhere in code
  fun1()
fun()

10 20 3 False


**Closures**

Closure: nonlocal variables attached to a returned function

In [ ]:
def foo():
  a =5
  def bar():
    print(a)
  return bar
func = foo()
func()

5


In [ ]:
type(func.__closure__)

tuple

In [ ]:
func.__closure__[0].cell_contents

5

**Decorators**

wrapper placed around a function that changes a function's behavior

decorators are just functions that take a function as an argument and return a modified version of that function

In [ ]:
def double_args(func):
  return func
#decorator here does nothing

In [ ]:
@double_args
def multiply(a,b):
  return a*b

multiply(2,2)

4

Usually helpful for decorator to return new function to return

In [ ]:
def double_args(func):
  #define a new function that we can modify
  def wrapper(a,b):
    #call the passed in function, but double each argument
    return func(a * 2,b * 2)
  #return new function
  return wrapper

new_multiply = double_args(multiply)
new_multiply(1,5)

20

Decorator syntax:

In [ ]:
@double_args
def multiply(a,b):
  return a*b

multiply(2,2)

16

**Example decorators**

In [ ]:
import time

def timer(func):
  """A decorator that prints how long a function took to run:

  Args: 
    func (callable): The function bein decorated.
  
  Returns:
    callable: the decorated function.
    """
  def wrapper(*args, **kwargs):
    t_start = time.time() # get current time
    result = func(*args, **kwargs) # call the decorated function and store result
    t_total = time.time() - t_start
    print(f'{func.__name__} took {t_total}s')
    return result
  return wrapper


In [ ]:
@timer
def sleep_n_seconds(n):
  time.sleep(n)
sleep_n_seconds(5)

sleep_n_seconds took 5.0051047801971436s


## Lambda Functions

In [ ]:
add = lambda x, y: x + y
add(1, 2)

#equivalent to:
# def add(x,y):
  #return x + y


3

So why would you ever want to use such a thing? Primarily, it comes
down to the fact that everything is an object in Python, even functions themselves! That means that functions can be passed as arguments to functions

Anonymous function - one that is defined without a name

.map()

In [ ]:
nums = [48,6,9,21,1]
square_all = map(lambda num: num ** 2, nums)
square_all
#returns map object

In [ ]:
list(square_all)

[2304, 36, 81, 441, 1]

.filter()

In [ ]:
# Create a list of strings: fellowship
fellowship = ['frodo', 'samwise', 'merry', 'pippin', 'aragorn', 'boromir', 'legolas', 'gimli', 'gandalf']

# Use filter() to apply a lambda function over fellowship: result
result = filter(lambda member: len(member) > 6, fellowship)

# Convert result to a list: 
list(result)

['samwise', 'aragorn', 'boromir', 'legolas', 'gandalf']

.reduce()

In [ ]:
from functools import reduce 
# Create a list of strings: stark
stark = ['robb', 'sansa', 'arya', 'brandon', 'rickon']

# Use reduce() to apply a lambda function over stark: result
result = reduce(lambda item1, item2: item1+item2, stark)

result

'robbsansaaryabrandonrickon'

As an example of this, suppose we have some data stored in a list of
dictionaries:


In [ ]:
data = [{'first':'Guido', 'last':'Van Rossum', 'YOB':1956},
 {'first':'Grace', 'last':'Hopper', 'YOB':1906},
 {'first':'Alan', 'last':'Turing', 'YOB':1912}]


Now suppose we want to sort this data. Python has a sorted function that does this:

In [ ]:
sorted([2,4,3,5,1,6])

[1, 2, 3, 4, 5, 6]

But dictionaries are not orderable: we need a way to tell the function
how to sort our data. We can do this by specifying the key function,
a function which given an item returns the sorting key for that item:


In [ ]:
# sort alphabetically by first name
sorted(data, key=lambda item: item['first'])

[{'YOB': 1912, 'first': 'Alan', 'last': 'Turing'},
 {'YOB': 1906, 'first': 'Grace', 'last': 'Hopper'},
 {'YOB': 1956, 'first': 'Guido', 'last': 'Van Rossum'}]

In [ ]:
# sort by year of birth
sorted(data, key=lambda item: item['YOB'])

[{'YOB': 1906, 'first': 'Grace', 'last': 'Hopper'},
 {'YOB': 1912, 'first': 'Alan', 'last': 'Turing'},
 {'YOB': 1956, 'first': 'Guido', 'last': 'Van Rossum'}]

# 6-OOP

## a-Notes

Most basic, intro programming is usually *procdural*, done in sequence of steps.
Object-oriented programming is about code as *interactions of objects*
 * Great for building frameworks and tools
 * Helps organize code to make it more easily reusable

Fundamental concepts in OOP are *objects* and *classes* <br />
Class is an abstract template while an object is a concrete representation of a class

Object is a data structure incorporating information about: 
  * State   - Attributes
  * Behavior- Methods

Encapsulation - Concept that state/behavior are tied together, bundling data with code operating on it


Classes are like blueprints for objects - outline possible states and behaviors <br >
In Python everything is an object and every object has a class (even function class) <br >
Use type() to find the class of any object <br >
Python attributes are represented by variables and methods are represented by functions.

### Constructor 

Used to add data to an object when creating it. <br />
Constructor '__init__()' method is called every time an object is created. <br />
<br />
Good place to set the default values of an object <br />
If possible, try to avoid defining attributes outside the constructor. 
  * Ensures all attributes are created when the object is created
  * More readable and maintainable code


**Best Practices**

1. Initialize attributes in __init__() constructor
2. Naming - CamelCase for classes, lower_snake_case for functions and attributes
3. Keep self as self. Using self is a convention, and any word could be used for first variable for method. Always treated as object reference. But using self is best practice for readability. 
4. Use docstrings (see below)

In [ ]:
#docstrings
class MyClass:
  """This class does nothing""" #This is our docstring
  pass

cl = MyClass()

##b-Simple Class

In [ ]:
! pip install faker

In [ ]:
from faker import Faker
import numpy as np
fake = Faker()

Sales Lead Tracker

In [ ]:
class Lead():                 #another naming convention - classes starting Uppercase
  """ A sales lead class """

  def __init__(self):         #dunder - double under score - initialization function 
    self.lead_type = str(np.random.choice(['Business', 'Personal', 'Non-Profit'], size=1)[0])
    self.phone_number = fake.phone_number()
    self.email = fake.email()
    self.name = fake.name()
    self.status = 'Lead'
    self.activities = 0
    self.purchases = []


  def add_activity(self):
    self.activities = self.activities +1
    return (self.activities)

  def add_purchase(self, amount):
    if not isinstance(amount, (int, float)):
      return (print('you must add a int or float for amount'))
    else:
      self.purchases.append(amount)

In [ ]:
lead = Lead()
#instantiating our object

In [ ]:
lead.email

'xcarter@hotmail.com'

In [ ]:
lead.purchases

[]

In [ ]:
lead.add_purchase(amount = 100)

In [ ]:
lead.purchases

[100]

# 7-Datetimes

* construction
* math and timedeltas
* from number 
* parsing

In [ ]:
import datetime
import time

## a-Creating datetime objects

In [ ]:
#from now
n = datetime.datetime.now()
n

datetime.datetime(2020, 10, 19, 13, 20, 11, 666557)

In [ ]:
#utc now - colab server also in utc time, so returns same result
u = datetime.datetime.now()
u

datetime.datetime(2020, 10, 19, 13, 51, 50, 8376)

In [ ]:
type(n)

datetime.datetime

In [ ]:
#manually creating
datetime.datetime(2020,3,25,4,20)

datetime.datetime(2020, 3, 25, 4, 20)

## b-Methods/attributes

In [ ]:
n.date()

datetime.date(2020, 10, 19)

In [ ]:
n.time()

datetime.time(13, 20, 11, 666557)

In [ ]:
str(n)
#string representation of datetime object

'2020-10-19 13:20:11.666557'

In [ ]:
n.day

19

In [ ]:
n.month

10

In [ ]:
#monday is 0, sunday is 6
n.weekday()

0

### Timedeltas and duration calculations

In [ ]:
#creating two timestamps 5 seconds apart
x = datetime.datetime.utcnow()
time.sleep(5)
y = datetime.datetime.utcnow()

print(x)
print(y)

2020-10-19 13:42:25.135193
2020-10-19 13:42:30.140612


In [ ]:
tmp = y-x
tmp

datetime.timedelta(0, 5, 5419)

In [ ]:
type(tmp)

datetime.timedelta

Using Timedeltas:

In [ ]:
x = datetime.datetime(year= 2020, month = 10, day=13)
y = datetime.datetime(year = 2020, month=10, day=25)

print(x)
print(str(y))

2020-10-13 00:00:00
2020-10-25 00:00:00


In [ ]:
#number of days between these two datetimes
(y-x) / datetime.timedelta(days = 1)
#returns how many increments of 1 day are between the two datetimes

12.0

In [ ]:
#how many hours 
(y-x) / timedelta(hours = 1)
#288 hours between the two 

288.0

## c-Datetimes To/From Strings

Hold onto this resource:
https://strftime.org/  <br >

2 Useful functions: strptime and strftime
 * strptime converts a string into a datetime object
 * strftime converts a datetime object to a string based on specified parameters


### Strptime() - string to dt

In [ ]:
x = '2020-03-12'   #ymd
y = '12-31-19'   #mdy
z = '2020-01-01 01:25:28' #ymd hms

In [ ]:
# parse x
datetime.datetime.strptime(x, '%Y-%m-%d')
#returns datetime object from string representation as specified by arguments in strptime (parse time) function

datetime.datetime(2020, 3, 12, 0, 0)

In [ ]:
#parse y
datetime.datetime.strptime(y, '%m-%d-%y')

datetime.datetime(2019, 12, 31, 0, 0)

In [ ]:
#parse z 
datetime.datetime.strptime(z, '%Y-%m-%d %X')

datetime.datetime(2020, 1, 1, 1, 25, 28)

### Strftime() - dt to string

In [ ]:
eddie = datetime.datetime.now()

In [ ]:
eddie.strftime('%d-%B-%y %H_%M_%S|')

'19-October-20 13_47_51|'

In [ ]:
#human readable form of the day of the week
eddie.strftime('%A')

'Monday'

## d-Date Sequences

In [ ]:
dt = datetime.datetime(2020, 10, 1)
end = datetime.datetime(2020, 10, 2)
step = datetime.timedelta(hours=1)

In [ ]:
# how much time in between two dates
(end - dt) / step

24.0

In [ ]:
# add the timedelta 
hours = []
while dt < end:
  hours.append(dt)
  dt = dt + step

hours

[datetime.datetime(2020, 10, 1, 0, 0),
 datetime.datetime(2020, 10, 1, 1, 0),
 datetime.datetime(2020, 10, 1, 2, 0),
 datetime.datetime(2020, 10, 1, 3, 0),
 datetime.datetime(2020, 10, 1, 4, 0),
 datetime.datetime(2020, 10, 1, 5, 0),
 datetime.datetime(2020, 10, 1, 6, 0),
 datetime.datetime(2020, 10, 1, 7, 0),
 datetime.datetime(2020, 10, 1, 8, 0),
 datetime.datetime(2020, 10, 1, 9, 0),
 datetime.datetime(2020, 10, 1, 10, 0),
 datetime.datetime(2020, 10, 1, 11, 0),
 datetime.datetime(2020, 10, 1, 12, 0),
 datetime.datetime(2020, 10, 1, 13, 0),
 datetime.datetime(2020, 10, 1, 14, 0),
 datetime.datetime(2020, 10, 1, 15, 0),
 datetime.datetime(2020, 10, 1, 16, 0),
 datetime.datetime(2020, 10, 1, 17, 0),
 datetime.datetime(2020, 10, 1, 18, 0),
 datetime.datetime(2020, 10, 1, 19, 0),
 datetime.datetime(2020, 10, 1, 20, 0),
 datetime.datetime(2020, 10, 1, 21, 0),
 datetime.datetime(2020, 10, 1, 22, 0),
 datetime.datetime(2020, 10, 1, 23, 0)]

In [ ]:
len(hours)

24

## e-Numeric Representations of Datetimes

In [ ]:
vh = datetime.datetime.now()

In [ ]:
vh.timestamp()
#returns number of seconds since 1/1/1970

1603115530.481486

In [ ]:
datetime.datetime.fromtimestamp(1603115530.481486)
# number can represent a datetime object if properly formatted

datetime.datetime(2020, 10, 19, 13, 52, 10, 481486)

In [ ]:
vh - timedelta(seconds = 1603115530.481486)
#origin point is 1/1/1970

datetime.datetime(1970, 1, 1, 0, 0)

In [ ]:
datetime.datetime.fromtimestamp(-100000000)
#can put in negative timestamp to get dates before origin

datetime.datetime(1966, 10, 31, 14, 13, 20)