##Random

In [ ]:
import random

In [ ]:
strang = 'hello there'
lizt = [1 , 2, strang]

In [ ]:
random.choices(strang, k = 5)

['h', 'l', 'e', 'l', ' ']

In [ ]:
random.choices(lizt, k = 5)

['hello there', 1, 2, 2, 2]

### Numpy Random

In [ ]:
import numpy as np


In [ ]:
np.random.rand(5,3)
#generates 5 x3 matrix of numbers 0 - 1

array([[0.5250864 , 0.66877512, 0.81076551],
       [0.93609202, 0.95517624, 0.75258903],
       [0.67219773, 0.27912732, 0.04189674],
       [0.95788658, 0.04320205, 0.17990407],
       [0.26154379, 0.32803245, 0.46517089]])

In [ ]:
np.random.choice([1,2,3,4,5], size = 2, replace=False)
#returns array drawn randomly from a list

array([5, 1])

# 1. Statistical Simulation

##Probability Distributions

### Uniform Distributions

Discrete:

In [ ]:
dice = [1,2,3,4,5,6]
rolls = []
for i in range(10):
  roll = np.random.choice(dice, size =1)
  rolls.append(roll[0])
rolls

[4, 1, 6, 4, 6, 2, 1, 3, 3, 2]

Continuous:

In [ ]:
u = np.random.uniform(low = 0,high = 10, size = 10)
u

array([8.9692491 , 9.99344425, 2.88470413, 4.68327315, 9.2220519 ,
       8.34777672, 2.29127168, 2.6293878 , 4.48070417, 1.9801273 ])

### Normal Distribution

In [ ]:
norm = np.random.normal(size = 100)
#default is mean of 0 and std dev of 1
norm

array([ 0.62625034,  0.11952023, -0.19598775, -0.07376829, -0.41965739,
        0.06078763, -1.82705087,  0.64217983, -0.3299172 , -0.5637501 ,
       -0.34413443,  0.57808975, -1.01368517, -0.91874014, -1.16624487,
        0.09269804,  0.28328091, -0.9935626 , -0.05621289,  2.58830417,
        1.41496878,  0.13107082, -0.21155491, -1.19990154, -0.14397683,
       -0.12034613,  0.23361048, -0.20544179,  1.18852733,  1.93620963,
        0.53778962,  0.13422691, -1.1039733 ,  1.04417227, -0.16801546,
       -1.52991911,  0.28351355, -1.37955539,  1.13820595, -1.2026026 ,
        1.29317175, -0.73950457, -0.69899122,  1.83936271,  0.74965101,
        0.46969799, -0.47052086, -0.12753045,  0.1382747 , -0.32903445,
       -0.55777211,  0.28469899,  1.14241665,  0.9808839 ,  0.69316922,
        0.39260817,  0.38686276,  1.93771085,  0.50751   ,  0.67448476,
       -0.97808493,  0.1668198 , -2.09878317,  1.02995432, -0.65485151,
       -1.34003478, -0.41143047, -1.27610979, -1.28005967, -0.28

In [ ]:
norm1 = np.random.normal(loc = 100, scale = 50, size = 100)
#mean of 100 and stdev of 50
norm1

array([117.72974605, 122.83640085,  71.47632337,  29.17572602,
        78.9013219 ,  99.93014309, 117.58730318, 125.58702346,
       186.79204042, 157.19557249, 224.66696371, 206.58743464,
        87.99719043, 128.35913737, 151.0074486 ,  99.85030363,
       161.7250455 ,  10.15890035, 153.3784894 , 130.31000185,
        78.83249307,  34.10336452,  87.83481182, 110.1068429 ,
       158.74422985, 130.12358479,  33.02463434,  21.65665651,
       103.45784758,  62.93075746,  34.78958049,  14.49064384,
        43.94360376, 146.58144126,  41.92084869,  78.57379073,
       136.9401438 ,  86.21756613,  94.90013413, 124.11001212,
       192.71553096, 158.0765483 , 174.90661405, 140.30050736,
       110.91299124, 102.98149796,  40.59238378,  56.75464122,
       142.00564674,  54.37836405,  93.96814686, 143.91519713,
        94.22615937, 149.96936843, 145.51506477,  58.35937318,
        51.14423377,  41.38974285,  28.31060965, 129.79664085,
       108.8533387 ,  60.88229012,  74.16934883, 105.71

### Binomial Distribution

In [ ]:
binom = np.random.binomial(n = 1, p = .5, size = 1)
binom
#single coin flip

array([1])

Arguments allow to specify "n"-#of events and "size"- #of sims run

In [ ]:
binom = np.random.binomial(n = 10, p = .5, size = 1)
binom
#how many heads over ten flips

array([5])

In [ ]:
binom = np.random.binomial(n = 10, p = .5, size = 10)
binom
#how many heads over ten flips simulated 10 times

array([5, 5, 4, 6, 4, 7, 7, 5, 3, 8])

### Poisson Distribution

In [ ]:
p = np.random.poisson(100, 10)
#distribution given an expected value of 100
p

array([ 95, 116, 120, 121,  87,  95,  96,  84, 100,  94])

In [ ]:
p[p>110]

array([116, 120, 121])

## Hypothesis Testing

### One sample t-test

In [ ]:
# create a 1d array from a normal dist 0/1
# size = 15
x = np.random.normal(size = 15)
x

array([-0.4786146 ,  1.20536306,  0.62823891, -0.50183059,  1.36817538,
       -0.18828541,  2.230829  ,  0.26553004,  0.66670124,  0.67217061,
       -0.97737883, -0.6869869 , -0.41826047, -1.51883469,  0.69217648])

In [ ]:
# ttest from scipy

stats.ttest_1samp(x, 0)

Ttest_1sampResult(statistic=0.7644546456883278, pvalue=0.4572886666242084)

In [ ]:
# try this again - larger sample
# size = 1000
x = np.random.normal(size = 1000)

stats.ttest_1samp(x, 0)

Ttest_1sampResult(statistic=-0.12258858449918589, pvalue=0.902457550605909)

 as sample size increases from the distribution, pvalue gets larger.  Much less unlikely that sample is drawn from a different distribution

breakout exercise:

In [ ]:
# create an array with mean 85 and standard deviation of 3
# test against a population mean of 91
x = np.random.normal(size = 50, loc = 85, scale = 3)
#                                loc - location aka mean
#                                          scale = std dev
x

array([80.42461006, 83.65117001, 87.79968149, 82.64667811, 85.08737527,
       83.96350941, 87.53552393, 87.87342761, 83.49807925, 88.15795187,
       86.56913055, 78.40532188, 89.72774985, 82.63654279, 84.60993906,
       87.91448937, 86.0332711 , 87.25632544, 86.56490508, 84.29955217,
       86.98993668, 82.90976934, 86.19153047, 84.45614755, 86.50356294,
       86.936522  , 84.3226056 , 85.03410076, 76.88620883, 83.2799564 ,
       88.39377058, 86.76181422, 85.67345854, 86.85620967, 83.87870454,
       90.16431477, 82.81888307, 85.2594838 , 86.86937486, 86.46857549,
       83.43677788, 81.29858668, 82.65091662, 82.56924531, 82.63881265,
       85.45089184, 89.71117704, 87.02139669, 82.76308134, 84.45559675])

In [ ]:
stats.ttest_1samp(x, 91)
#super low p-value indicates that our sample differs significantly from the population
#super low probability that difference is due to randomness

Ttest_1sampResult(statistic=-15.422153275870771, pvalue=1.9547547576516358e-20)

In [ ]:
stats.ttest_1samp(x,85 )

Ttest_1sampResult(statistic=0.17187988605706295, pvalue=0.8642398698594639)

### Two sample t-test

In [ ]:
# lets create two random normal, 100/15, 115/15, size=100
x = np.random.normal(100,15,100)
y = np.random.normal(115,15,100)
stats.ttest_ind(x,y)

Ttest_indResult(statistic=-7.670517544438497, pvalue=7.582573599952088e-13)

In [ ]:
x = np.random.normal(100,15,100)
y = np.random.normal(105,15,100)
stats.ttest_ind(x,y)

Ttest_indResult(statistic=-3.0621302042167877, pvalue=0.0025030386140617675)

In [ ]:
x = np.random.normal(100,15,100)
y = np.random.normal(101,15,100)
stats.ttest_ind(x,y)

Ttest_indResult(statistic=-1.650667971387152, pvalue=0.10039166996989235)

## Simulation Assignment 

In [ ]:
import numpy as np
import random 

class dice_game():
    """A class to study and simulate outcomes of proposed game"""
    
    def __init__(self):
        self.wallet = []
        self.games_played = []
        self.players = 50
    
    def avg_rounds(self):
        if len(self.games_played) == 0:
            print('No simulated data')
        else:    
            ar = int(np.mean(np.array(self.games_played)))
            return ar
    
    def profit(self):
        if len(self.wallet) == 0:
            print('No simulated data')
        else:
            prof = np.sum(10 - np.array(self.wallet))
            return prof
        
    def simulate(self):
        self.wallet = []
        self.games_played = []
        for _ in range(self.players):
            
            pc = 10
            gp = 0 
            while pc > 0 and gp < 25:
                pc -= 1
                roll1 = random.choice([1,2,3,4,5,6])
                roll2 = random.choice([1,2,3,4,5,6])
                roll3 = 0 # reassigned if 3rd roll is necessary
                total = roll1+roll2


                if total <= 9:
                    roll3 = random.choice([1,2,3,4,5,6])
                elif total == 10:
                    roll3 = np.random.choice([random.choice([1,2,3,4,5,6]), 0], size = 1, p = [.7,.3])[0]
                    
                grand_total = total + roll3

                #payout
                if grand_total <= 11 or grand_total in [16,17]:
                    payout = 0
                elif grand_total == 12:
                    payout = 1 
                elif grand_total in [13,14,15]:
                    payout = 2
                elif grand_total == 18:
                    payout = 5 


                pc += payout
                gp += 1

            self.wallet.append(pc)
            self.games_played.append(gp)



In [ ]:
dg = dice_game()
print(dg.wallet)
print(dg.games_played)
print(dg.players)
dg.profit()
dg.avg_rounds()

[]
[]
50
No simulated data
No simulated data


In [ ]:
dg.simulate()

In [ ]:
print(dg.wallet)
print(dg.games_played)
print(dg.players)
dg.profit()
dg.avg_rounds()

[0, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0]
[13, 16, 12, 13, 20, 14, 16, 15, 25, 20, 19, 16, 24, 20, 12, 16, 15, 16, 12, 10, 15, 15, 15, 19, 21, 21, 19, 16, 17, 12, 17, 18, 25, 11, 16, 25, 19, 16, 19, 19, 14, 19, 23, 25, 21, 13, 25, 12, 17, 18]
50


17

## Other sims

Birthday Sim

In [ ]:
# Draw a sample of birthdays & check if each birthday is unique
days = np.arange(1,366)
people = 2

def birthday_sim(people):
    sims, unique_birthdays = 2000, 0 
    for _ in range(sims):
        draw = np.random.choice(days, size=people, replace=True)
        if len(draw) == len(set(draw)): 
            unique_birthdays += 1
    out = 1 - unique_birthdays / sims
    return out

birthday_sim(50)

0.9735

In [ ]:
while (people > 0):
    prop_bds = birthday_sim(people)
    if prop_bds > 0.5: 
        break
    people += 1

print("With {} people, there's a 50% chance that two share a birthday.".format(people))

With 24 people, there's a 50% chance that two share a birthday.


Game of thirteen <br > 

A famous French mathematician Pierre Raymond De Montmart, who was known for his work in combinatorics, proposed a simple game called as Game of Thirteen. You have a deck of 13 cards, each numbered from 1 through 13. Shuffle this deck and draw cards one by one. A coincidence is when the number on the card matches the order in which the card is drawn. For instance, if the 5th card you draw happens to be a 5, it's a coincidence. You win the game if you get through all the cards without any coincidences. Let's calculate the probability of winning at this game using simulation.

In [ ]:
# Pre-set constant variables
deck, sims, coincidences = np.arange(1, 14), 10000, 0

for sim in range(sims):
    # Draw all the cards without replacement to simulate one game
    draw = np.random.choice(deck, size=len(deck), replace=False)
    # Check if there are any coincidences
    coincidence = (draw == list(np.arange(1, 14))).any()
    if coincidence == True: 
        coincidences += 1

# Calculate probability of winning
prob_of_winning = 1- (coincidences / sims)
print("Probability of winning = {}".format(prob_of_winning))


Probability of winning = 0.3748


Two of a kind

In [ ]:
deck_of_cards = [('Heart', 0), ('Heart', 1), ('Heart', 2), ('Heart', 3), ('Heart', 4), ('Heart', 5), ('Heart', 6), ('Heart', 7), ('Heart', 8), ('Heart', 9), ('Heart', 10), ('Heart', 11), ('Heart', 12), ('Club', 0), ('Club', 1), ('Club', 2), ('Club', 3), ('Club', 4), ('Club', 5), ('Club', 6), ('Club', 7), ('Club', 8), ('Club', 9), ('Club', 10), ('Club', 11), ('Club', 12), ('Spade', 0), ('Spade', 1), ('Spade', 2), ('Spade', 3), ('Spade', 4), ('Spade', 5), ('Spade', 6), ('Spade', 7), ('Spade', 8), ('Spade', 9), ('Spade', 10), ('Spade', 11), ('Spade', 12), ('Diamond', 0), ('Diamond', 1), ('Diamond', 2), ('Diamond', 3), ('Diamond', 4), ('Diamond', 5), ('Diamond', 6), ('Diamond', 7), ('Diamond', 8), ('Diamond', 9), ('Diamond', 10), ('Diamond', 11), ('Diamond', 12)]


In [ ]:
# Shuffle deck & count card occurrences in the hand
n_sims, two_kind = 10000, 0
for i in range(n_sims):
    np.random.shuffle(deck_of_cards)
    hand, cards_in_hand = deck_of_cards[0:5], {}
    for [suite, numeric_value] in hand:
        # Count occurrences of each numeric value
        cards_in_hand[numeric_value] = cards_in_hand.get(numeric_value, 0) + 1
    
    # Condition for getting at least 2 of a kind
    if max(cards_in_hand.values()) >=2: 
        two_kind += 1

print("Probability of seeing at least two of a kind = {} ".format(two_kind/n_sims))

Probability of seeing at least two of a kind = 0.4945 
